# -*- coding: utf-8 -*-
"""ml2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17e7RWTCp86fL6-eTqPmsYS44QpXXlJIb
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.dummy import DummyClassifier
from sklearn.metrics import accuracy_score, classification_report
import warnings
warnings.filterwarnings("ignore")

# Загрузка данных
train = pd.read_csv('/content/train_data.csv')
test = pd.read_csv('/content/test_data.csv')
sam_sub = pd.read_csv('/content/sample_submission_data.csv')

# Предобработка данных
categorical_cols = train.select_dtypes(include=['object']).columns.intersection(test.columns)
for col in categorical_cols:
    train[col].fillna(train[col].mode()[0], inplace=True)
    test[col].fillna(test[col].mode()[0], inplace=True)

# Заполнение пропусков для числовых колонок
numeric_cols = [col for col in train.select_dtypes(include=['float64', 'int64']).columns if col in test.columns]

train[numeric_cols] = train[numeric_cols].fillna(train[numeric_cols].mean())
test[numeric_cols] = test[numeric_cols].fillna(test[numeric_cols].mean())

test.isnull().sum()

train.isnull().sum()

# Кодирование категориальных переменных
train = pd.get_dummies(train, drop_first=True)
test = pd.get_dummies(test, drop_first=True)
# Убедимся, что тестовый набор имеет те же колонки, что и тренировочный
test = test.reindex(columns=train.columns, fill_value=0)
# Определение признаков и целевой переменной
X = train.drop('Depression', axis=1)
y = train['Depression']

# Разделение данных на тренировочную и валидационную выборки
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

"""🤖 Model Building (using DummyClassifier and XGBoost)

"""

# 1. Измерение качества константного предсказания
most_frequent_class = y_train.mode()[0]
y_pred_constant = [most_frequent_class] * len(y_val)
accuracy_constant = accuracy_score(y_val, y_pred_constant)
print(f'Accuracy of constant prediction: {accuracy_constant}')

# 2. Бейзлайновая модель с DummyClassifier
# Я выбрала DummyClassifier, так как он позволяет установить базовый уровень точности для задачи классификации. Использовала стратегию 'most_frequent', чтобы предсказать наиболее частый класс.
dummy_model = DummyClassifier(strategy='most_frequent', random_state=42)
dummy_model.fit(X_train, y_train)
y_pred_dummy = dummy_model.predict(X_val)

# 3. Оценка качества DummyClassifier
accuracy_dummy = accuracy_score(y_val, y_pred_dummy)
print(f'Accuracy of DummyClassifier: {accuracy_dummy}')
print("\nClassification Report for DummyClassifier:\n", classification_report(y_val, y_pred_dummy))

# 4. Обучение XGBClassifier (продвинутая модель)
xgb_model = XGBClassifier(use_label_encoder=False, eval_metric='logloss')

xgb_model.fit(X_train, y_train)

y_pred_xgb = xgb_model.predict(X_val)

print("Accuracy:", accuracy_score(y_val, y_pred_xgb))
print("\nClassification Report:\n", classification_report(y_val, y_pred_xgb))